[02-19-2021-10-32-01][EXCEPTION]: Traceback (most recent call last):
  File "/home/spotify/projects/zeus/src/application/spotify/Spotify.py", line 32, in getMyIp
    result = json.loads(json_str)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 13 (char 13)

[02-19-2021-10-32-04][SUCCESS]: My ip is : None
